# Generated by Django 4.2.7 on 2023-12-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('phone_number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('boolean_field', models.BooleanField()),
                ('date_field', models.DateField()),
                ('date_time_field', models.DateTimeField()),
                ('cls_duration', models.DurationField()),
                ('file_uplode', models.FileField(upload_to='files/')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
